# Generated by Django 5.2.1 on 2025-10-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
