# Generated by Django 5.2.1 on 2025-10-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal_system', '0002_lead_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('admin', 'Admin Lead'), ('partner_own', 'Partner Own Lead'), ('partner_referral', 'Partner Referral')], max_length=20),
        ),
    ]
