# Generated by Django 5.2.1 on 2025-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal_system', '0004_alter_partner_options_partner_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('admin', 'Admin Lead'), ('partner_own', 'Partner Own Lead'), ('partner_referral', 'Partner Referral')], default='partner_own', max_length=20),
        ),
    ]
