# Generated by Django 5.2.1 on 2025-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal_system', '0007_rename_notes_lead_additional_notes_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadnote',
            name='follow_up_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
