# Generated by Django 5.2.1 on 2025-11-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal_system', '0008_leadnote_follow_up_completed_leadnote_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
    ]
